import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, ChevronRight, Compass, GraduationCap, Lightbulb, ShieldCheck } from 'lucide-react';
import { HeroArt } from '@/components/science-art';

export const metadata: Metadata = { title: 'Về BananaLearning' };
export default function AboutPage() {
  return <div className="container page-section about-page"><div className="breadcrumbs"><Link href="/">Trang chủ</Link><ChevronRight size={14} /><span>Về BananaLearning</span></div><section className="about-hero"><div><div className="section-kicker">ĐỊNH VỊ TRI THỨC · DẪN LỐI TƯ DUY</div><h1>Mở một góc nhìn mới<br />về việc học.</h1><p>BananaLearning là thư viện mô phỏng PhET HTML5 dành cho việc học và khám phá: kết nối Vật lí, Hóa học, Toán học, Sinh học và Khoa học Trái Đất với những trải nghiệm tương tác ngay trong trình duyệt.</p><Link className="button primary" href="/thu-vien">Khám phá thư viện <ArrowRight size={18} /></Link></div><HeroArt /></section><section className="about-values">{[
    { icon: Compass, title: 'Học qua khám phá', text: 'Bắt đầu từ một câu hỏi thay vì một đáp án. Thay đổi tham số, quan sát kết quả và tự tìm ra mối liên hệ.' },
    { icon: GraduationCap, title: 'Gần gũi với người học', text: 'Giao diện tiếng Việt, chủ đề theo môn và thông tin nguồn rõ ràng. Mô phỏng có thể phục vụ nhiều cấp học; không tự gán lớp THPT khi nguồn không cung cấp.' },
    { icon: ShieldCheck, title: 'Đơn giản và riêng tư', text: 'Không đăng nhập, không cơ sở dữ liệu. Ghi chú và chủ đề đã lưu chỉ nằm trên trình duyệt của bạn.' },
  ].map(({ icon: Icon, title, text }) => <article className="content-card" key={title}><Icon size={30} strokeWidth={1.5} /><h2>{title}</h2><p>{text}</p></article>)}</section><section className="content-card about-status"><Lightbulb size={34} /><div><div className="section-kicker">MÔ PHỎNG THẬT · KHÁM PHÁ CHỦ ĐỘNG</div><h2>Một thư viện mở từ PhET</h2><p>Các mô phỏng HTML5 độc lập của PhET được lưu cục bộ cùng ứng dụng và nhúng vào khung tương tác. Mỗi mô phỏng tự quản lí các thao tác bên trong; BananaLearning cung cấp thư viện, điều hướng và không gian ghi chú, không phải tác giả của các mô phỏng.</p><p>Nội dung mô phỏng thuộc <a href="https://phet.colorado.edu" target="_blank" rel="noopener noreferrer">PhET Interactive Simulations · University of Colorado Boulder</a>. Xem <a href="https://phet.colorado.edu/en/licensing" target="_blank" rel="noopener noreferrer">thông tin giấy phép chính thức</a> và thông tin nguồn của từng chủ đề. Các bản HTML5 thông thường được cấp phép theo <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener noreferrer">CC BY-NC 4.0</a> cho sử dụng phi thương mại; tích hợp vào sản phẩm thương mại, thu phí hoặc có quảng cáo cần giấy phép thương mại từ CU Boulder. Giữ nguyên logo PhET và thông tin ghi nhận nguồn trong mô phỏng. Ưu tiên bản tiếng Việt khi có; một số mô phỏng dùng ngôn ngữ thay thế do bản dịch chưa có hoặc chưa tải được.</p><p>BananaLearning sử dụng logo do nhóm cung cấp. Bố cục và bảng màu được phát triển từ mẫu tham khảo ban đầu; các mô phỏng giữ nguyên nhận diện và nguồn PhET. Đây là giao diện học tập thử nghiệm, không phải dịch vụ chính thức của PhET.</p><Link className="view-all" href="/huong-dan#nhung-html">Tìm hiểu cách sử dụng và thử HTML cục bộ <ArrowRight size={17} /></Link></div></section></div>;
}
