import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Bookmark, ChevronRight, FileCode2, NotebookPen, Scan, Search, ShieldCheck } from 'lucide-react';

export const metadata: Metadata = { title: 'Hướng dẫn sử dụng' };
const steps = [
  { icon: Search, title: 'Chọn một chủ đề', text: 'Đến thư viện, tìm theo từ khóa hoặc lọc theo môn học và ngôn ngữ. Bạn có thể tìm bằng tiếng Việt có dấu hoặc không dấu.' },
  { icon: Scan, title: 'Tự tay khám phá mô phỏng', text: 'Mở một chủ đề để chạy mô phỏng PhET HTML5 ngay trong trình duyệt. Thử thay đổi tham số, đưa ra dự đoán rồi quan sát kết quả. Mô phỏng được tải từ tệp cục bộ của ứng dụng.' },
  { icon: NotebookPen, title: 'Ghi lại điều bạn nhận ra', text: 'Chuyển sang thẻ Ghi chú để lưu dự đoán và quan sát. Ghi chú được lưu tự động trên trình duyệt đang sử dụng.' },
  { icon: Bookmark, title: 'Giữ lại chủ đề yêu thích', text: 'Nhấn biểu tượng dấu trang để lưu chủ đề. Trở lại mục Đã lưu trong thư viện bất cứ khi nào bạn muốn.' },
];
export default function GuidePage() {
  return <div className="container page-section guide-page"><div className="breadcrumbs"><Link href="/">Trang chủ</Link><ChevronRight size={14} /><span>Hướng dẫn</span></div><div className="page-heading"><div><div className="section-kicker">DỄ BẮT ĐẦU, TỰ DO KHÁM PHÁ</div><h1>Hướng dẫn sử dụng</h1><p>Mọi điều bạn cần để khám phá thư viện PhET trên BananaLearning.</p></div></div><div className="guide-steps">{steps.map(({ icon: Icon, title, text }, index) => <article className="guide-step" key={title}><span className="guide-number">0{index + 1}</span><Icon size={28} strokeWidth={1.6} /><h2>{title}</h2><p>{text}</p></article>)}</div>
    <section id="nhung-html" className="content-card embed-guide"><div className="section-kicker"><FileCode2 size={17} /> MÔ PHỎNG CỤC BỘ · THỬ HTML TÙY CHỌN</div><h2>Mở PhET có sẵn hoặc thử tệp riêng</h2><p>Thư viện đã nhúng các mô phỏng PhET HTML5 độc lập. Bạn không cần tự chọn tệp để sử dụng chúng. Tính năng thử HTML trên máy là lựa chọn bổ sung dành cho người muốn kiểm tra nội dung riêng.</p><div className="embed-options"><article><span className="outline-pill">CÁCH 01 · THƯ VIỆN PHET</span><h3>Mở mô phỏng có sẵn</h3><ol><li>Chọn một chủ đề trong thư viện.</li><li>Chờ mô phỏng tải trong khung tương tác.</li><li>Dùng các điều khiển bên trong mô phỏng; mở rộng khung khi cần.</li></ol><p>Ưu tiên bản tiếng Việt khi có. Nếu bản dịch chưa có hoặc chưa tải được, thư viện có thể dùng bản ngôn ngữ thay thế; hãy kiểm tra thông tin ngôn ngữ và nguồn của chủ đề. Mỗi mô phỏng có thiết kế và thao tác riêng.</p></article><article><span className="outline-pill">CÁCH 02 · THỬ TỆP RIÊNG</span><h3>Chọn tệp HTML trên máy</h3><ol><li>Mở một chủ đề và nhấn <strong>Thử nhúng tệp HTML</strong>.</li><li>Chọn tệp <code>.html</code> hoặc <code>.htm</code> dưới 10 MB.</li><li>Gỡ tệp thử để quay lại mô phỏng có sẵn.</li></ol><p>Tệp chỉ chạy trong phiên hiện tại, không được tải lên máy chủ. Dùng HTML độc lập có CSS và JavaScript nhúng sẵn; thao tác chọn tệp không cấp quyền đọc các tài nguyên tương đối khác trong thư mục trên máy.</p></article></div><div className="security-note"><ShieldCheck size={22} /><div><strong>Chỉ thử nội dung từ nguồn tin cậy</strong><p>Mô phỏng chạy trong iframe có giới hạn quyền. Tệp HTML thử trên máy được cách li với trang cha, nhưng vẫn có thể gửi yêu cầu mạng. Không mở tệp lạ hoặc nhập dữ liệu nhạy cảm vào mô phỏng. Việc điều khiển tham số diễn ra bên trong từng mô phỏng, không phải qua trang thư viện.</p></div></div></section>
    <section className="faq-section"><div className="section-kicker">CÓ THỂ BẠN ĐANG THẮC MẮC</div><h2>Một vài câu hỏi thường gặp</h2>{[
      ['Có cần tạo tài khoản không?', 'Không. Website không có đăng nhập hoặc cơ sở dữ liệu. Bạn có thể mở thư viện và sử dụng mô phỏng ngay.'],
      ['Các mô phỏng đến từ đâu?', 'Đây là mô phỏng PhET HTML5 của University of Colorado Boulder, được lưu cục bộ và nhúng vào ứng dụng. BananaLearning cung cấp giao diện thư viện và ghi chú, không sở hữu hay tự phát triển các mô phỏng PhET. Liên kết nguồn và giấy phép giúp bạn đối chiếu với nhà cung cấp.'],
      ['Có được dùng mô phỏng cho mục đích thương mại không?', 'Các bản PhET HTML5 thông thường được cấp phép CC BY-NC 4.0 cho sử dụng phi thương mại. Tích hợp vào sản phẩm thương mại, thu phí hoặc có quảng cáo cần giấy phép thương mại từ CU Boulder. Hãy đọc điều kiện sử dụng chính thức qua liên kết ở chân trang và thông tin nguồn của từng mô phỏng; giữ logo PhET hiển thị, không sửa đổi logo và giữ nguyên thông tin ghi nhận nguồn.'],
      ['Tại sao một số mô phỏng không có tiếng Việt?', 'Không phải mô phỏng nào cũng có bản dịch tiếng Việt tải được. Thư viện ưu tiên tiếng Việt và dùng ngôn ngữ thay thế khi cần; nhãn ngôn ngữ phản ánh tệp thực tế, không phải cam kết toàn bộ nội dung tương tác đã được Việt hóa.'],
      ['Ghi chú và chủ đề đã lưu nằm ở đâu?', 'Chúng nằm trong localStorage của trình duyệt này, không đồng bộ sang thiết bị khác. Xóa dữ liệu trình duyệt hoặc dùng chế độ riêng tư có thể làm mất thông tin. Nếu trình duyệt chặn lưu trữ, website vẫn dùng được nhưng dữ liệu có thể chỉ tồn tại trong phiên.'],
      ['Tại sao mô phỏng hoặc HTML thử không hiển thị đúng?', 'Thử tải lại khung và kiểm tra trình duyệt. Với tệp chọn trên máy, hãy dùng HTML độc lập; tài nguyên tương đối khác không được đọc tự động. Mô phỏng phụ thuộc dịch vụ bên ngoài hoặc quyền bổ sung có thể không hoạt động trong khung cách li.'],
      ['Có dùng được trên điện thoại không?', 'Giao diện thích ứng với điện thoại, máy tính bảng và máy tính. Khả năng thao tác còn tùy từng mô phỏng PhET; một số nội dung thuận tiện hơn trên màn hình lớn.'],
    ].map(([question, answer]) => <details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section><div className="guide-bottom"><p>Sẵn sàng cho câu hỏi đầu tiên?</p><Link href="/thu-vien" className="button primary">Đến thư viện <ArrowRight size={18} /></Link></div>
  </div>;
}
